### ISSUE TITLE
"ComboAddress native statistics ringbuffer" breaks building on FreeBSD

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2031]
Introduced in commit 4eb26e0fdeca34c6fcb77c52a621c3fd8c1c9ae8, it breaks the build on FreeBSD with:

```
depbase=`echo statbag.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; c++ -DHAVE_CONFIG_H -I. -I..   -I.. -I..  -I/usr/local/include -I../pdns/ext/rapidjson/include  -I../pdns/ext/yahttp -I../pdns/ext/polarssl/include/    -I/usr/local/include/p11-kit-1 -I/usr/local/include  -I/usr/local/include/lua52  -DSYSCONFDIR=\"/usr/local/etc\"  -DPKGLIBDIR=\"/usr/local/lib/pdns\"  -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -pthread -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -g -O2 -MT statbag.o -MD -MP -MF $depbase.Tpo -c -o statbag.o statbag.cc && mv -f $depbase.Tpo $depbase.Po
statbag.cc:216:53: error: no viable conversion from 'iterator' (aka '__map_iterator<typename __base::iterator>') to 'typename map<ComboAddress, unsigned
      int>::const_iterator' (aka '__map_const_iterator<typename __base::const_iterator>')
  for(typename map<T, unsigned int>::const_iterator i=res.begin();i!=res.end();++i)
                                                    ^ ~~~~~~~~~~~
statbag.cc:310:16: note: in instantiation of member function 'StatRing<ComboAddress, ComboAddress::addressOnlyLessThan>::get' requested here
template class StatRing<ComboAddress, ComboAddress::addressOnlyLessThan >;
               ^
/usr/include/c++/v1/map:564:24: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'iterator'
      (aka '__map_iterator<typename __base::iterator>') to 'const std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::map<ComboAddress,
      unsigned int, std::__1::less<ComboAddress>, std::__1::allocator<std::__1::pair<const ComboAddress, unsigned int> > >::__value_type,
      std::__1::__tree_node<std::__1::map<ComboAddress, unsigned int, std::__1::less<ComboAddress>, std::__1::allocator<std::__1::pair<const ComboAddress,
      unsigned int> > >::__value_type, void *> *, long> > &' for 1st argument
class _LIBCPP_TYPE_VIS __map_const_iterator
                       ^
/usr/include/c++/v1/map:588:5: note: candidate constructor not viable: no known conversion from 'iterator' (aka '__map_iterator<typename __base::iterator>') to
      'std::__1::__tree_const_iterator<std::__1::map<ComboAddress, unsigned int, std::__1::less<ComboAddress>, std::__1::allocator<std::__1::pair<const
      ComboAddress, unsigned int> > >::__value_type, std::__1::__tree_node<std::__1::map<ComboAddress, unsigned int, std::__1::less<ComboAddress>,
      std::__1::allocator<std::__1::pair<const ComboAddress, unsigned int> > >::__value_type, void *> *, long>' for 1st argument
    __map_const_iterator(_TreeIterator __i) _NOEXCEPT : __i_(__i) {}
    ^
/usr/include/c++/v1/map:590:5: note: candidate constructor not viable: no known conversion from '__map_iterator<__tree_iterator<struct std::__1::map<union
      ComboAddress, unsigned int, struct ComboAddress::addressOnlyLessThan, class std::__1::allocator<struct std::__1::pair<const union ComboAddress, unsigned
      int> > >::__value_type, __node_pointer, [...]>>' to '__map_iterator<__tree_iterator<struct std::__1::map<union ComboAddress, unsigned int, struct
      std::__1::less<union ComboAddress>, class std::__1::allocator<struct std::__1::pair<const union ComboAddress, unsigned int> > >::__value_type,
      __non_const_node_pointer, [...]>>' for 1st argument
    __map_const_iterator(
    ^
1 error generated.
*** Error code 1
```

**Comment by cmouse** [comment]
FreeBSD 9
/usr/local/include/boost/move/core.hpp: At global scope:
/usr/local/include/boost/move/core.hpp: In instantiation of 'boost::rv<ComboAddress>':
statbag.cc:175:   instantiated from 'void StatRing<T, Comp>::account(const T&) [with T = ComboAddress, Comp = ComboAddress::addressOnlyLessThan]'
statbag.hh:96:   instantiated from here
/usr/local/include/boost/move/core.hpp:68: error: base type 'ComboAddress' fails to be a struct or class type

**Comment by cmouse** [comment]
Works with gcc 4.8, won't work with gcc 4.7

**Comment by ahupowerdns** [comment]
Fixed.
