### ISSUE TITLE
dnsdist: Fails to build with Boost 1.70 (master snapshot)

### ISSUE THREAD

**Issue by jbeich** [PowerDNS/pdns#7556]
Regressed by boostorg/smart_ptr@eac641186738. Found on FreeBSD on dnsdist-1.3.3. May not affect other platforms due to header botlegging.

```c++
dnsdist-lua-vars.cc:99:61: error: expected unqualified-id
                                       {"BADSIG",   ERCode::BADSIG  },
                                                            ^
/usr/include/sys/signal.h:490:17: note: expanded from macro 'BADSIG'
#define BADSIG          SIG_ERR
                        ^
/usr/include/sys/signal.h:139:18: note: expanded from macro 'SIG_ERR'
#define SIG_ERR         ((__sighandler_t *)-1)
                        ^
1 error generated.
```

**Comment by Habbie** [comment]
> botlegging

Can you elaborate on this?

**Comment by rgacogne** [comment]
I guess we could `#undef BADSIG` like we already do in `dns.hh`..
