### PR TITLE
libssl: fix compilation issues on older openssl versions

### PR DESCRIPTION
**Pull request by chbruyand**
Fix `missing SSL_CTX_use_cert_and_key` function on openssl version < 1.1.1 by disabling pkcs12 support

Introduced in https://github.com/PowerDNS/pdns/pull/11027

```
libssl.cc: In function 'std::unique_ptr<ssl_ctx_st, void (*)(ssl_ctx_st*)> libssl_init_server_context(const TLSConfig&, std::map<int, std::basic_string<char> >&)':
libssl.cc:809:82: error: 'sk_X509_free' was not declared in this scope
       auto ca = std::unique_ptr<STACK_OF(X509), void(*)(STACK_OF(X509)*)>(captr, sk_X509_free);
                                                                                  ^~~~~~~~~~~~
libssl.cc:811:11: error: 'SSL_CTX_use_cert_and_key' was not declared in this scope
       if (SSL_CTX_use_cert_and_key(ctx.get(), cert.get(), key.get(), ca.get(), 1) != 1) {
           ^~~~~~~~~~~~~~~~~~~~~~~~
libssl.cc:811:11: note: suggested alternative: 'SSL_CTX_use_certificate'
       if (SSL_CTX_use_cert_and_key(ctx.get(), cert.get(), key.get(), ca.get(), 1) != 1) {
           ^~~~~~~~~~~~~~~~~~~~~~~~
           SSL_CTX_use_certificate
```

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
`#if ... defined(sk_X509_free)` only works if it a preprocessor symbol, is it?

**Comment by Habbie** [comment]
> `#if ... defined(sk_X509_free)` only works if it is a preprocessor symbol, is it?

You're right, and it isn't. This PR leads to
```
      throw std::runtime_error("PKCS12 files are not supported by your openssl version");
```
on my Debian 10 with OpenSSL 1.1.1d.

**Review by rgacogne — APPROVED** [review]

**Review by omoerbeek — APPROVED** [review]
