### ISSUE TITLE
dnsdist fails to build with clang 4.0.0

### ISSUE THREAD

**Issue by cpu82** [PowerDNS/pdns#4913]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

dnsdist fails to build with clang 4.0 likely due to https://github.com/llvm-mirror/clang/commit/4b6ad14285f3
```
% /usr/bin/clang -v
FreeBSD clang version 4.0.0 (branches/release_40 292009) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```
```
ext/json11/json11.cpp:153:24: error: invalid operands to binary expression
      ('nullptr_t' and 'nullptr_t')
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
               ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ext/json11/json11.cpp:209:5: note: in instantiation of member function
      'json11::Value<json11::Json::Type::NUL, nullptr_t>::less' requested here
    JsonNull() : Value(nullptr) {}
    ^
```
Full build log: http://sprunge.us/DWTf

### Environment

 - Operating system: FreeBSD 12.0-CURRENT/amd64
 - Software version: dnsdist-1.1.0
 - Software source: tar.gz

### Steps to reproduce

1.  build with CC="cc" CXX="c++" CPP="cpp" ./configure --bindir=/usr/local/sbin --enable-dnscrypt  --enable-libsodium --enable-re2 --prefix=/usr/local

**Comment by rgacogne** [comment]
Thank you for reporting this. It looks like upstream [1] still has the same issue, so it should probably be reported there too. It would be easier for everyone to have an upstream fix.

[1]: https://github.com/dropbox/json11

**Comment by rgacogne** [comment]
Upstream fixed the issue in https://github.com/dropbox/json11/pull/92, I'll check if we can easily backport the fix.
