### ISSUE TITLE
PowerDNS compilation errors on gcc 4.4

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#284]
I've been looking into Ubuntu Lucid Lynx 10.04, what has to become the new LTS. Here gcc 4.4 is shipped by default:

```
wijnand@brain:~$ gcc -v
Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-3ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-3ubuntu1) 
```

Gcc 4.4 is more strict than traditional versions of gcc so it seems. It is confused about wether to use std::exception or boost::exception. Attached you will find patches that addresses this issue and make both pdns and pdns-recursor compile with gcc 4.4 in Ubuntu 10.04.
