### PR TITLE
Backport json11 fixes from upstream

### LINKED ISSUE #4913: dnsdist fails to build with clang 4.0.0
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

dnsdist fails to build with clang 4.0 likely due to https://github.com/llvm-mirror/clang/commit/4b6ad14285f3
```
% /usr/bin/clang -v
FreeBSD clang version 4.0.0 (branches/release_40 292009) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```
```
ext/json11/json11.cpp:153:24: error: invalid operands to binary expression
      ('nullptr_t' and 'nullptr_t')
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
               ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ext/json11/json11.cpp:209:5: note: in instantiation of member function
      'json11::Value<json11::Json::Type::NUL, nullptr_t>::less' requested here
    JsonNull() : Value(nullptr) {}
    ^
```
Full build log: http://sprunge.us/DWTf

### Environment

 - Operating system: FreeBSD 12.0-CURRENT/amd64
 - Software version: dnsdist-1.1.0
 - Software source: tar.gz

### Steps to reproduce

1.  build with CC="cc" CXX="c++" CPP="cpp" ./configure --bindir=/usr/local/sbin --enable-dnscrypt  --enable-libsodium --enable-re2 --prefix=/usr/local

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Backports `json11` fixes from upstream.
Hopefully fixes #4913.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added regression tests
- [ ] added unit tests

### CODE REVIEW

**Comment by zeha** [comment]
is this a backport or actually an update of the files? the latter would probably be best?

**Comment by rgacogne** [comment]
You're right, it's actually an update of the files to 07fe48880402214fd66357b09bda33a18d784e76
