### ISSUE TITLE
auth 4.0.4 fails to build with clang 4.0

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#5458]
- Program: Authoritative
 - Issue type: Bug report

### Short description
dnsdist fails to build with clang 4.0 likely due to llvm-mirror/clang@4b6ad14

```
% /usr/bin/clang -v
FreeBSD clang version 4.0.0 (branches/release_40 292009) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```

```
ext/json11/json11.cpp:153:24: error: invalid operands to binary expression
      ('nullptr_t' and 'nullptr_t')
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
               ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ext/json11/json11.cpp:209:5: note: in instantiation of member function
      'json11::Value<json11::Json::Type::NUL, nullptr_t>::less' requested here
    JsonNull() : Value(nullptr) {}
    ^
```

### Environment

 - Operating system: FreeBSD 12-STABLE
 - Software version: pdns-4.0.4
 - Software source: tarball

### Steps to reproduce

1. CC="cc" CXX="c++" CPP="cpp" ./configure --disable-static  --with-modules=""  --with-dynmodules="pipe bind gmysql gpgsql"  --docdir="/usr/local/share/doc/powerdns"  --sysconfdir="/usr/local/etc/pdns"  --with-boost="/usr/local" --with-mysql=/usr/local --enable-botan1.10  --enable-libsodium --with-pgsql=/usr/local --without-protobuf --disable-tools --without-lua --with-luajit --prefix=/usr/local

**Comment by rgacogne** [comment]
We need to backport https://github.com/PowerDNS/pdns/pull/4940 to auth-4.0.x , it has been backported to rec-4.0.x only so far.

**Comment by rgacogne** [comment]
Fixed by #5491.
