### ISSUE TITLE
OpenSSL 1.1 not detected by configure

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#4051]
In Debian we've got reports from builds with OpenSSL 1.1.0 (beta?), where configure would fail:

```
Trying link with OPENSSL_LDFLAGS=; OPENSSL_LIBS=-lcrypto; OPENSSL_INCLUDES=
configure:18616: g++ -o conftest -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='"4.0.0~alpha3-1.Debian"' -std=gnu++11  -Wdate-time -D_FORTIFY_SOURCE=2 -fPIE -pie -Wl,-z,relro -Wl,-z,now -latomic   conftest.cpp -lcrypto  -lboost_thread -lboost_system -pthread  >&5
conftest.cpp: In function 'int main()':
conftest.cpp:38:17: error: too few arguments to function 'void CRYPTO_free(void*, const char*, int)'
 CRYPTO_free(NULL)
                 ^
In file included from conftest.cpp:34:0:
/usr/include/openssl/crypto.h:267:6: note: declared here
 void CRYPTO_free(void *ptr, const char *file, int line);
      ^
```

Please consider supporting OpenSSL 1.1.0 in 4.0.0.
