### ISSUE TITLE
dnsdist: Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [PowerDNS/pdns#7091]
After boostorg/logic@23cd89d4c80f build fails. See [error log](https://ptpb.pw/c1ye).
```c++
dnsdist-lua.cc:76:10: error: no viable conversion from returned value of type 'boost::logic::tribool' to function return type 'bool'
  return g_noLuaSideEffect==true;
         ^~~~~~~~~~~~~~~~~~~~~~~
```
