### ISSUE TITLE
rec_channel.cc:72: error: 'mkstemp' was not declared in this scope

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#175]
I had to add <cstdlib> to rec_channel.cc to get it to build with GCC4.3
