### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#687]
Attempting to configure and install pdns 3.2 and it fails after issuing the make command with the following error:

lua-pdns.cc: In function void popResourceRecordsTable(lua_State_, const string&, std::vector<DNSResourceRecord>&):
lua-pdns.cc:126:35: error: lua_objlen was not declared in this scope
lua-pdns.cc: In constructor PowerDNSLua::PowerDNSLua(const string&):
lua-pdns.cc:220:20: error: lua_open was not declared in this scope
make[4]: *_\* [lua-pdns.o] Error 1
make[4]: Leaving directory `/root/pdns-3.2/pdns'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory`/root/pdns-3.2/pdns'
make[2]: **\* [all] Error 2
make[2]: Leaving directory `/root/pdns-3.2/pdns'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/pdns-3.2'
make: **\* [all] Error 2

Here is my configure line:

./configure \
--prefix=/usr/local/powerdns_server \
--enable-cryptopp \
--enable-pdns_server \
--with-boost=/usr \
--with-modules="" \
--with-dynmodules="gmysql gpgsql" \
--with-mysql \
--with-mysql-lib=/usr/lib \
--with-mysql-includes=/usr/include \
--with-pgsql \
--with-pgsql-lib=/usr/lib \
--with-pgsql-includes=/usr/include \
--with-lua \
--disable-recursor

This same configure line does work with 3.1
