### ISSUE TITLE
pdns-auth: --enable-verbose-logging (DLOG) seems to break compile in master

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#4170]
Commit e490ae9b1cd81107b2d0551b87672216d12022b4 seems to break compiling with "--enable-verbose-logging" (DLOG) in current master (cad0349621450e414c95b9c265b89b0f0df7cc15).
Reverting that commit seems to help (at least with compiling).

```
  CXX    packethandler.o
In file included from dnspacket.hh:54:0,
                 from packetcache.hh:35,
                 from packethandler.cc:25:
packethandler.cc: In member function ‘DNSPacket* PacketHandler::questionOrRecurse(DNSPacket*, bool*)’:
packethandler.cc:1390:199: error: operands to ?: have different types ‘const char [7]’ and ‘DNSName’
 st ANY query for '"<<target<<"', id="<<sd.domain_id<<": weDone="<<weDone<<", weHaveUnauth="<<weHaveUnauth<<", weRedirected="<<weRedirected<<", haveAlias='"<<(haveAlias.empty() ? "(none)"
                                                                                                                                                                                 ^
logger.hh:117:17: note: in definition of macro ‘DLOG’
 #define DLOG(x) x
                 ^
make[3]: *** [packethandler.o] Error 1
```

Centos 6.8, devtoolset-4

**Comment by Habbie** [comment]
I filed a PR for this earlier today

On July 13, 2016 3:58:41 PM GMT+02:00, Andreas Jakum <notifications@github.com> wrote:
>Commit e490ae9b1cd81107b2d0551b87672216d12022b4 seems to break
>compiling with "--enable-verbose-logging" (DLOG) in current master
>(cad0349621450e414c95b9c265b89b0f0df7cc15).
>Reverting that commit seems to help (at least with compiling).
>
>
>  CXX    packethandler.o
>In file included from dnspacket.hh:54:0,
>                 from packetcache.hh:35,
>                 from packethandler.cc:25:
>packethandler.cc: In member function ‘DNSPacket*
>PacketHandler::questionOrRecurse(DNSPacket*, bool*)’:
>packethandler.cc:1390:199: error: operands to ?: have different types
>‘const char [7]’ and ‘DNSName’
>st ANY query for '"<<target<<"', id="<<sd.domain_id<<":
>weDone="<<weDone<<", weHaveUnauth="<<weHaveUnauth<<",
>weRedirected="<<weRedirected<<", haveAlias='"<<(haveAlias.empty() ?
>"(none)"
>                                                                      ^
>logger.hh:117:17: note: in definition of macro ‘DLOG’
> #define DLOG(x) x
>                 ^
>make[3]: *** [packethandler.o] Error 1
>
>
>Centos 6.8, devtoolset-4
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/4170

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
