### ISSUE TITLE
Please add support for mbedtls 2.0.0

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#2652]
checking for crypt in -lcrypt... yes
checking whether to enable verbose logging... no
checking for library containing sha1_hmac... no
configure: error: use of system polarssl requested but not found

**Comment by mortenstevens** [comment]
Note: The workaround with commit https://github.com/rubenk/pdns/commit/b90709b47220ad3abecbc382d97ec7ec38fbb34d doesn't work with mbedtls 2.0.

**Comment by rubenk** [comment]
Next time, please post config.log.

```
configure:18342: g++ -o conftest -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fstack-protector --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -DLDAP_DEPRECATED -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lrt conftest.cpp -lmbedtls   >&5
/tmp/ccknKtR8.o: In function `main':
/home/ruben/pkg/pdns/pdns-3.4.5/conftest.cpp:48: undefined reference to `sha1_hmac'
collect2: error: ld returned 1 exit status
configure:18342: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "pdns"
| #define PACKAGE_TARNAME "pdns"
| #define PACKAGE_VERSION "3.4.5"
| #define PACKAGE_STRING "pdns 3.4.5"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "pdns"
| #define VERSION "3.4.5"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_TM_GMTOFF 1
| #define HAVE_SYS_MMAN_H 1
| #define HAVE_MMAP 1
| #define HAVE_LUA 1
| #define HAVE_LUA_H 1
| #define HAVE_BOOST 1
| #define HAVE_BOOST_FOREACH_HPP 1
| #define HAVE_BOOST_PROGRAM_OPTIONS_HPP 1
| #define HAVE_BOOST_ARCHIVE_TEXT_OARCHIVE_HPP 1
| #define HAVE_BOOST_TEST_UNIT_TEST_HPP 1
| #define HAVE_STRCASESTR 1
| #define HAVE_LIBDL 1
| #define HAVE_LIBCRYPT 1
| #define HAVE_IPV6 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char sha1_hmac ();
| int
| main ()
| {
| return sha1_hmac ();
|   ;
|   return 0;
| }
```

**Comment by rubenk** [comment]
This is more involved than I thought, since mbedtls changed its api quite a bit. It's gonna take a while to fix this, you might want to back out your mbedtls upgrade in Rawhide for the time being.

**Comment by mortenstevens** [comment]
@rubenk 
Peter confirmed to provide an upstream patch next week. This should be enough for us.

**Comment by Habbie** [comment]
I did not promise anything.

**Comment by mortenstevens** [comment]
@Habbie 
All right. I see you said "maybe next week". I've overlooked. We would be happy to have the patch next week, because then I'm on vacation starting from the week after that. In the meantime I would refer to Ruben as co-maintainer for PowerDNS.

**Comment by rubenk** [comment]
Habbie is on holiday, and I'm seriously considering taking one too ;). If you don't want to leave pdns broken in Rawhide, please revert mbedtls so we can write a proper patch without pressure. This is crypto stuff we're talking about, so taking shortcuts is risky and unnecessary.

**Comment by mortenstevens** [comment]
@rubenk 
Yes I understand. But we have now other packages which are linked against mbedtls 2.0. For example: dislocker And this package has been also built against the latest mbedtls package on F23 and rawhide.

There is another possibility for F23 and rawhide: Temporary switch to the internal polarssl version as shipped with the pdns source package? Then we have more time to add support for mbedtls 2.0. What do you think?

**Comment by rubenk** [comment]
Next time please don't push a major library update without checking that its reverse dependencies don't break. You have maintainership of both mbedtls and powerdns so I don't understand why you did this.

As for fixing it, reverting to the built-in polarssl is probably fine for Rawhide but not for F-23.

**Comment by mortenstevens** [comment]
@rubenk 
Fedora has naturally the latest stable packages in the development branch. I've been waiting two weeks after the mbedtls 2.0 release before pushing it to rawhide and F23. Note: F23 is also a development branch and currently nearly the same as rawhide. That was a conscious decision. In addition, we have enough time until the F23 release for fixing small issues like this.

**Comment by rubenk** [comment]
I strongly disagree with everything you just said. In those 2 weeks you could have checked if pdns gained support for mbedtls 2.0. You say this is a small issue, have you looked into what is needed to fix this? I'm afraid that if we don't do anything about it F-23 will end up with a broken pdns because you didn't test the update, decided to ignore any advice I give and now expect someone else to pick up the pieces because you're going on holiday. This is not how open source works.

Anyway, the upstream bug tracker is not the place for these discussions so lets take this offline.
