### ISSUE TITLE
auth: Building docs fails if Python >= 3.10 is used

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#12204]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Sphinx fails during building of documentation if Python >= 3.10 is used.

### Environment
 - Operating system: Debian Bookworm
 - Software version: master
 - Software source: compiling from Git checkout

### Steps to reproduce
1. Ensure that 'python3' on the system is at least version 3.10.
2. Checkout 'master' branch.
3. Run `configure` and `make` steps.
4. See failure at the end of the process when an exception occurs while running Sphinx.

### Expected behaviour
Docs are built successfully :-)

### Actual behaviour
```
Exception occurred:
  File "/home/kpfleming/git-personal/pdns/docs/.venv/lib/python3.10/site-packages/sphinxcontrib/openapi.py", line 43, in _do_resolve
    if isinstance(node, collections.Mapping) and '$ref' in node:
AttributeError: module 'collections' has no attribute 'Mapping'
```

### Other information
The code responsible for this is [here](https://github.com/PowerDNS/sphinxcontrib-openapi/blob/2f9dd7c6be753a6f5569e4dfcb346b46bd81c25a/sphinxcontrib/openapi.py#L43), but that repository does not allow issues to be opened! `collections.Mapping` became `collections.abc.Mapping` in Python 3.10.

**Comment by Habbie** [comment]
https://github.com/PowerDNS/sphinxcontrib-openapi/tree/use-jsondomain-pdns-py3.10 might fix this

**Comment by kpfleming** [comment]
Confirmed, this works with Python 3.10.
