### PR TITLE
Fix build with LibreSSL 2.7

### PR DESCRIPTION
**Pull request by Sp1l**
### Short description
LibreSSL 2.7 implements OpenSSL 1.1 API leading to conflicts in method names

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>

### CODE REVIEW

**Comment by Habbie** [comment]
> compiled and tested this code

Did you?

**Comment by Sp1l** [comment]
Hi @Habbie 
Clearly not well enough... And not against the master branch. Meanwhile a version of the patch landed in FreeBSD ports. These were tested by me in FreeBSD ports.
https://bugs.freebsd.org/227183 https://bugs.freebsd.org/227184
Looks like a typo 😭 I redid the work in my private pdns fork. From the CI logs:
```
opensslsigners.cc:37:5: error: missing ')' in expression
 #if (OPENSSL_VERSION_NUMBER < 0x1010000fL || \
```
I'll cycle back to this and retest. Expect a follow up later in the week.

**Comment by Sp1l** [comment]
> Note that I wouldn't be surprised to see the same fix needed in pdns/dnsdistdist/tcpiohandler.cc too if we want to enable DNS over TLS on FreeBSD.

Correct. Just checked and LibreSSL 2.7 has both `CRYPTO_set_id_callback` and `CRYPTO_set_locking_callback`.

The change is not for FreeBSD, it is currently only/mostly OpenBSD that is affected as they have LibreSSL 2.7 in the base OS. For FreeBSD users they must be using `security/libressl-devel` from ports.
Once I've landed sufficient patches for ports, I will switch `security/libressl` to 2.7 branch in FreeBSD.

**Comment by Habbie** [comment]
dnsdist 1.3.0 compiles fine with DNS-over-TLS support on an OpenBSD 6.3 snapshot from this week, with LibreSSL 2.7.2, without anything like this patch.

**Comment by Habbie** [comment]
@Sp1l ping

**Comment by Sp1l** [comment]
Thanks for the poke @Habbie . Meanwhile I've updated the security/libressl port on FreeBSD to 2.7.2.
I'll check up on dnsdist and pdns builds.

**Comment by RvdE** [comment]
When @Sp1l created this PR, the security/libressl port was still on the 2.6.x branch, which worked fine (only security/libressl-devel was on the 2.7.x branch). Since april 28th the ports has been updated to version 2.7.2 (and is currently on 2.7.3), which does require the patch.

Hopefully that clarifies things enough to get this into master, so I can remove the patch from my port on FreeBSD

**Comment by tcely** [comment]
A similar patch is being used for AlpineLinux too. https://github.com/alpinelinux/aports/commit/c841cf3b79ba701cc99a6f3b3fed37278e00606c

**Comment by aerique** [comment]
I had similar build issues on Void Linux which uses LibreSSL as well.

Cloned this branch and merged master into it. It compiled fine and I'm currently using it to work on another issue. I have not run into any problems so far.

**Comment by rgacogne** [comment]
The fix looks good to me, compatibility with OpenSSL 1.1.0's API has been implemented in LibreSSL 2.7 so our own compatibility layer is colliding with it. I believe we should also backport this fix to 4.1.x and in dnsdist's `tcpiohandler.cc`.

**Comment by rgacogne** [comment]
It turns out that dnsdist compiles correctly with 2.7.3 since it does not redefine the various accessors that collide in the auth and rec. I'm very concerned however about the locking code. OpenSSL >= 1.1.0 does not need it anymore, but looking at the code it's absolutely not obvious that `LibreSSL` >= 2.7.0 doesn't, and this PR removes it. If `LibreSSL` >= 2.7.0 does indeed still need it, merging this PR would cause race conditions, so in the end I don't think we should merge this as it is.
I would be OK to merge a PR removing the `RSA_` and `ECDSA_` helpers with `LibreSSL` >= 2.7.0, but unless someone can prove to me that the locking code is not needed I don't think we should remove it.

**Comment by zeha** [comment]
`CRYPTO_w_lock` and similar appear to be quite in use in current libressl.

**Comment by Sp1l** [comment]
Thanks for picking this up!

**Comment by github-k8n** [comment]
Any news on this?
Is the locking code still needed with LibreSSL >= 2.8.0 (2.8.1)?
Or any other way to make libressl work with pdns?

**Comment by Habbie** [comment]
I want to release auth 4.2.0-alpha soon; I'm going to need guidance on this from somebody who cares.

**Comment by rgacogne** [comment]
To sum up a bit, the main remaining question is whether LibreSSL >= 2.7.0 still need the application to provide and setup locking callbacks the way OpenSSL before 1.1.0 did.

If it does, and so far I have no reason to believe it does not, this PR should be amended so that the `RSA_*` and `ECDSA_*` helper functions are not defined when building with LibreSSL >= 2.7.0, because these do conflict with the versions present in LibreSSL, but should keep the locking callbacks in place to be thread-safe.

**Comment by Habbie** [comment]
Ping!

**Comment by omoerbeek** [comment]
Since LibreSSL 2.9 the CRYPTO_LOCK functions are deprecated and stubbed.
For LibreSSL 2.7 and 2.8 there are still needed. But for the callback functions the story is different:
`CRYPTO_set_id_callback` and `CRYPTO_set_locking_callback` are still implemented and are required for current LibreSSL. AFAIKS master seems to do the right thing: not implement the helpers, but do setup the lock callbacks.

Using OpenBSD current, on master rec, auth and dnsdist run and build fine.

**Comment by Habbie** [comment]
I agree with Otto, so I'm closing this.
