### PR TITLE
Remove `theLog` and `theL` and replace this with a global g_log

### LINKED ISSUE #6357: Fails to build with Boost 1.67
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
Fails to build with Boost 1.67 Beta1. The cause is related to,

   dns.hh:228    #define L theL() 

```
[  475s] g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I.. -pthread  -I../ext/json11 -I../ext/yahttp     -I/usr/include/p11-kit-1 
 -I/usr/include/lua5.3    -DSYSCONFDIR=\"/etc/pdns\" -DPKGLIBDIR=\"/usr/lib64/pdns\" -DLOCALSTATEDIR=\"/var\" -fPIE -DPI
E -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -fmessage-length=0 -grecord-gcc-swit
ches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-p
rotection -DLDAP_DEPRECATED -c -o common_startup.o common_startup.cc
[  475s] In file included from misc.hh:39:0,
[  475s]                  from dnsparser.hh:32,
[  475s]                  from protobuf.cc:3:
[  475s] dns.hh:228:11: error: expected nested-name-specifier before 'theL'
[  475s]  #define L theL()
[  475s]            ^
[  475s] dns.hh:228:11: error: there are no arguments to 'theL' that depend on a template parameter, so a declaration of
 'theL' must be available [-fpermissive]
[  475s]  #define L theL()
[  475s]            ^
[  475s] dns.hh:228:11: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
[  475s] In file included from /usr/include/boost/function_types/components.hpp:61:0,
[  476s]                  from /usr/include/boost/function_types/is_member_function_pointer.hpp:14,
[  476s]                  from /usr/include/boost/tti/detail/dmem_fun.hpp:11,
[  476s]                  from /usr/include/boost/tti/has_member_function.hpp:15,
[  476s]                  from /usr/include/boost/uuid/random_generator.hpp:19,
[  476s]                  from /usr/include/boost/uuid/uuid_generators.hpp:17,
[  476s]                  from protobuf.hh:34,
[  476s]                  from protobuf.cc:4:
[  476s] /usr/include/boost/function_types/detail/class_transform.hpp:28:35: error: type/value mismatch at argument 1 in template parameter list for 'template<class F, class T1> struct boost::mpl::apply1'
[  476s]  { typedef typename mpl::apply1<L,T>::type type; };
[  476s]                                    ^
[  476s] /usr/include/boost/function_types/detail/class_transform.hpp:28:35: note:   expected a type, got 'theL()'
[  476s] In file included from misc.hh:39:0,
[  476s]                  from dnsparser.hh:32,
[  476s]                  from protobuf.cc:3:
[  476s] dns.hh:228:11: error: expected nested-name-specifier before 'theL'
[  476s]  #define L theL()
[  476s]            ^

```

Full build logs are available at,

https://build.opensuse.org/build/home:adamm:boost_test/openSUSE_Tumbleweed/x86_64/pdns-recursor/_log

https://build.opensuse.org/build/home:adamm:boost_test/openSUSE_Tumbleweed/x86_64/pdns/_log

### Environment

 - Operating system: openSUSE Tumbleweed + Boost 1.67 Beta1

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Should close #6357 and should prevent issues in the future.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
:heart: ... but: `theLog` is the same length as `theL()`, except it's still a `#define`...

I'd suggest:
* kill theL altogether (needs .setName in receiver.cc, similar to what is done in pdns_recursor.cc)
* rename/move the `static Logger l` instance to s_log in global scope, and use that everywhere

That also gets rid of the `if(!pname.empty())` check that is done on every L/theL() usage.

File: pdns/recursor_cache.hh [hunk 1]
```diff
@@ -30,7 +30,7 @@
 #include <iostream>
 #include "dnsrecords.hh"
 #include <boost/utility.hpp>
-#undef L
+#undef s_log
```
Comment (rgacogne) [inline pdns/recursor_cache.hh]: I'm pretty sure all the `#undef s_log` can go since `s_log` is unlikely to collide with `boost::multi_index` in the same way `L` did.

File: pdns/logger.hh [hunk 2]
```diff
@@ -116,7 +116,7 @@ private:
   static pthread_key_t s_loggerKey;
 };
 
-extern Logger &theL(const string &pname="");
+extern Logger s_log;
```
Comment (rgacogne) [inline pdns/logger.hh]: So, hum, why `s_log`? This variable is not static so perhaps `g_log` would make more sense?

File: pdns/recursor_cache.hh (hunk 1 above)
Comment (pieterlexis) [reply pdns/recursor_cache.hh]: Ah yes, I caught some of them already, I'll search some some.

File: pdns/logger.hh (hunk 2 above)
Comment (pieterlexis) [reply pdns/logger.hh]: oh, indeed... This is me sucking at C++ because the `static` keyword gave all kinds of issues.. I'll se eif I can fit it with a fresh brain

Comment (zeha) [reply pdns/logger.hh]: right, i incorrectly suggested s_..., sorry!

**Comment by pieterlexis** [comment]
rebased to fix conflists, we should get this merged soon :)

**Comment by zeha** [comment]
```
pdns_recursor.cc: In function ‘int serviceMain(int, char**)’:
pdns_recursor.cc:3236:5: error: ‘L’ was not declared in this scope
     L<<Logger::Error<<"Unable to launch, udp-source-port-min is not a valid port number"<<endl;
     ^
pdns_recursor.cc:3242:5: error: ‘L’ was not declared in this scope
     L<<Logger::Error<<"Unable to launch, udp-source-port-max is not a valid port number or is smaller than udp-source-port-min"<<endl;
     ^
pdns_recursor.cc:3252:7: error: ‘L’ was not declared in this scope
       L<<Logger::Error<<"Unable to launch, udp-source-port-avoid contains an invalid port number: "<<part<<endl;
       ^
```

**Comment by zeha** [comment]
probably introduced by the rebase

**Comment by pieterlexis** [comment]
> probably introduced by the rebase

Ugh, I did search for `theL` when rebasing :), not `L`. Will fix

**Comment by pieterlexis** [comment]
rebased [one more time](https://www.youtube.com/watch?v=FGBhQbmPwH8), let's hope travis'll be green :)

**Comment by ahkok** [comment]
The zeromq backend module is still broken in the `auth` version `4.1.5` in the same way. (Boost `1.68`)

**Comment by Habbie** [comment]
@ahkok you have replied to a merged pull request; like on a closed ticket, these comments often go unnoticed and will definitely be forgotten. Please report your problem as a comment on a relevant open ticket, or file a new ticket.
